name: OFRandomTeleport
version: '0.1.0'
main: me.orbitium.oFRandomTeleport.OFRandomTeleport
api-version: '1.20'

commands:
  home:
  sethome:
  delhome:
  homes:
  tpa:
  tpaccept:
  rtp:
    permission: rtp.use

folia-supported: true