name: PterodactylBattles
version: '0.1.0'
main: me.orbitium.pterodactylBattles.PterodactylBattles
api-version: '1.21'
depend:
  - PterodactylManager
commands:
  gamenetwork:
    permission: gamenetwork.use
